### ISSUE TITLE
conanfile_directory was removed

### ISSUE THREAD

**Issue by fluidsonic** [bincrafters/conan-gmp#1]
Hey guys,

I cannot build this library from sources because [conanfile.py relies on `conanfile_directory` attribute](https://github.com/bincrafters/conan-gmp/blob/5212659a541b29ee150acde3d7004ca0861cc0e1/conanfile.py#L33) which [was removed](https://github.com/conan-io/conan/issues/2145).

Command:
```bash
conan install --build=missing -s compiler=clang -s compiler.version=6.0 -s compiler.libcxx=libstdc++14 ..
```

Output:
```
gmp/6.1.2@bincrafters/stable: ERROR: Package '5259980c28ce229fe2e57e2d23edbd1c056b2a1c' build failed
gmp/6.1.2@bincrafters/stable: WARN: Build folder ~/.conan/data/gmp/6.1.2/bincrafters/stable/build/5259980c28ce229fe2e57e2d23edbd1c056b2a1c
ERROR: gmp/6.1.2@bincrafters/stable: Error in build() method, line 33
	base_path = ("%s/" % self.conanfile_directory)
	AttributeError: 'GmpConan' object has no attribute 'conanfile_directory'
```

Looks like that `conanfile_directory` must be avoided.

**Comment by dimi309** [comment]
It looks like the solution is just to merge the testing branch to stable, since testing is way ahead. Can someone who has access do that?

Note that the appveyor build has to be removed, since it cannot work, as described here:
https://github.com/bincrafters/community/issues/65

Thanks!

**Comment by solvingj** [comment]
i'm doing now

**Comment by solvingj** [comment]
Fixed now.
